(in-package #:vacietis.libc.errno.h)
(in-readtable vacietis:vacietis)

(defvar errno-strings (make-array 35))

(defmacro deferr (name number msg)
  `(progn
     (setf (aref errno-strings ,number) (string-to-char* ,msg))
     (define ,name ,number ,msg)))

(deferr   EPERM	   1  "Operation not permitted (POSIX.1)")
(deferr   ENOENT   2  "No such file or directory (POSIX.1)")
(deferr   ESRCH	   3  "No such process (POSIX.1)")
(deferr   EINTR	   4  "Interrupted function call (POSIX.1)")
(deferr   EIO  	   5  "Input/output error")
(deferr   ENXIO	   6  "No such device or address (POSIX.1)")
(deferr   E2BIG	   7  "Argument list too long (POSIX.1)")
(deferr   ENOEXEC  8  "Exec format error (POSIX.1)")
(deferr   EBADF	   9  "Bad file descriptor (POSIX.1)")
(deferr   ECHILD   10 "No child processes (POSIX.1)")
(deferr   EAGAIN   11 "Resource  temporarily unavailable (POSIX.1)")
(deferr   ENOMEM   12 "Not enough space (POSIX.1)")
(deferr   EACCES   13 "Permission denied (POSIX.1)")
(deferr   EFAULT   14 "Bad address (POSIX.1)")
(deferr   ENOTBLK  15 "Block device required")
(deferr   EBUSY	   16 "Device or resource busy (POSIX.1)")
(deferr   EEXIST   17 "File exists (POSIX.1)")
(deferr   EXDEV	   18 "Improper link (POSIX.1)")
(deferr   ENODEV   19 "No such device (POSIX.1)")
(deferr   ENOTDIR  20 "Not a directory (POSIX.1)")
(deferr   EISDIR   21 "Is a directory (POSIX.1)")
(deferr   EINVAL   22 "Invalid argument (POSIX.1)")
(deferr   ENFILE   23 "Too many open files in system (POSIX.1)")
(deferr   EMFILE   24 "Too many open files (POSIX.1)")
(deferr   ENOTTY   25 "Inappropriate I/O control operation (POSIX.1)")
(deferr   ETXTBSY  26 "Text file busy (POSIX.1)")
(deferr   EFBIG	   27 "File too large (POSIX.1)")
(deferr   ENOSPC   28 "No space left on device (POSIX.1)")
(deferr   ESPIPE   29 "Invalid seek (POSIX.1)")
(deferr   EROFS	   30 "Read-only file system (POSIX.1)")
(deferr   EMLINK   31 "Too many links (POSIX.1)")
(deferr   EPIPE	   32 "Broken pipe (POSIX.1)")
(deferr   EDOM 	   33 "Mathematics argument out of domain of function (POSIX.1, C99)")
(deferr   ERANGE   34 "Result too large (POSIX.1, C99)")

(defvar errno 0)
